* Formal Models For System Verification course notes
  This document is a container of all the exercises that I did during
  the course of Formal Models For System Verification at University of
  Florence.  The professors are Michele Loreti
  (michele.loreti@unifi.it) and Mieke Massink
  (mieke.massink@unifi.it).

  All the document content is written using the Italian language, the
  code sources using the English language instead.

  Follow a short descriptions for each of the exercises present in
  this repository:
   
** CCS Process Algebra Implementation
   This is a Java implementation of a few basic SOS rules of the CCS
   process algebra. The implemented rules are: action prefixing,
   visible choice, parallel composition, restriction and recursion.

   The folder ``CCS-Implementation'' contains an Eclipse project and
   the unit tests in order to fix what we had in mind.
   
# ** How to use the Octave sources
#    In order to use the R sources is sufficient to run R
#    inside the folder the desired source are contained in.
